### ISSUE TITLE
Flex 布局

### ISSUE THREAD

**Issue by LinkChenzy** [LinkChenzy/blog#13]
### 1.Flex布局是什么
Flex 是 Flexible Box 的缩写，意为"弹性布局"，用来为盒状模型提供最大的灵活性。

任何一个容器都可以指定为 Flex 布局。
```css
.box{
    display:flex;
    display:-webkit-flex; /*浏览器是webkit内核的*/
    display:inline-flex; /*行内元素也可以使用 Flex 布局*/
}
```
***注意，设为 Flex 布局以后，子元素的float、clear和vertical-align属性将失效。***

### 2.基本概念

采用 Flex 布局的元素，称为 Flex 容器（flex container），简称"容器"。它的所有子元素自动成为容器成员，称为 Flex 项目（flex item），简称"项目"。

![image](https://user-images.githubusercontent.com/30339294/65014593-b42df580-d951-11e9-906a-d772c09caf20.png)

容器默认存在两根轴：水平的主轴（main axis）和垂直的交叉轴（cross axis）。主轴的开始位置（与边框的交叉点）叫做`main start`，结束位置叫做`main end`；交叉轴的开始位置叫做`cross start`，结束位置叫做`cross end`。

项目默认沿主轴排列。单个项目占据的主轴空间叫做`main size`，占据的交叉轴空间叫做`cross size`。

### 3.容器的属性

以下的6个属性设置在容器上
- flex-direction
- flex-wrap
- flex-flow
- justify-content
- align-items
- align-content

##### 3.1 `flex-direction` 属性决定主轴的方向（即项目的排列方向）
- row 默认值：主轴方向是水平方向，从左端开始
- row-reverse：主轴水平方向，从右端开始
- column：主轴垂直方向，从上端开始
- column-reverse：垂直方向，从下端开始
```css
.box{
    flex-direction:row | row-reverse | column | column-reverse;
}
```
![image](https://user-images.githubusercontent.com/30339294/65014526-8f398280-d951-11e9-930f-ca6cf8fc02ec.png)

##### 3.2 `flex-wrap` 默认情况下项目排在一条直线上，如果一条轴线排不下如何换行
- nowrap:默认不换行
- wrap:换行，第一行在上方
- wrap-reverse:换行，第一行在下方

```css
.box{
    flex-wrap:nowrap | wrap | wrap-reverse;
}
```
![image](https://user-images.githubusercontent.com/30339294/65014549-995b8100-d951-11e9-953a-6dae2475be54.png)

##### 3.3 `flex-flow` 是`flex-direction`和`flex-wrap`的简写，默认值为`row nowrap`
```css
.box{
    flex-flow: <flex-direction> || <flex-wrap>;
}
```

##### 3.4 `justify-content` 定义了项目在主轴的对齐方式
- flex-start：默认值，左对齐
- flex-end：右对齐
- center：居中
- space-between：两端对齐，项目之间的间隔相等
- space-around：每个项目两侧的间隔相等，所以项目之间的间隔要比项目与边框的间隔大一倍

```css
.box{
    justify-content:flex-start | flex-end | center | space-between | space-around ;
}
```
![image](https://user-images.githubusercontent.com/30339294/65014618-c60f9880-d951-11e9-9edb-548be7886144.png)

##### 3.5  `align-items` 定义项目在交叉轴上对齐方式
- flex-start:交叉轴的起点对齐
- flex-end:交叉轴的终点对齐
- center:交叉轴的中点对齐
- baseline:项目的第一行文字的基线对齐
- stretch:默认值，如果项目没有设置高度或者auto，将占满整个容器的高度

```css
.box{
    align-items: flex-start | flex-end | center | baseline | stretch ;
}
```
![image](https://user-images.githubusercontent.com/30339294/65014636-cf006a00-d951-11e9-83d7-e788201e8656.png)

##### 3.6 `align-content` 定义多根轴线的对齐方式，如果项目只有一根轴线该属性不起作用
- flex-start:与交叉轴的起点对齐
- flex-end:与交叉轴的终点对齐
- center:与交叉轴的中点对齐
- space-between:与交叉轴两端对齐，轴线之间的间隔平均分布
- space-around:每根轴线两侧的间隔都相等，轴线之间的间隔比轴线与边框的间隔大一倍
- stretch:默认值，轴线占满整个交叉轴

```css
.box{
    align-content: flex-start | flex-end | center | space-between | space-around | stretch ;
}
```
![image](https://user-images.githubusercontent.com/30339294/65014647-d6277800-d951-11e9-92aa-d9d0bb0a6870.png)

### 4.项目的属性（flex-item 子元素属性）
- order
- flex-grow
- flex-shrink
- flex
- align-self

##### 4.1 `order` 定义项目的排序顺序，数值越小排列越靠前，默认为0。

```css
.item{
    order: <integer>;
}
```

##### 4.2 `flex-grow` 定义项目的放大比例，默认为0，即如果有剩余空间也不放大

如果所有项目的`flex-grow`的属性都为1，则平分剩余空间（如果有的话），如果一个项目的`flex-grow`为2，其他的都为1，则前者占据的空间比其他的多一倍。

```css
.item{
    flex-grow:<number>;
}
```

##### 4.3 `flex-shrink` 定义项目的缩小的比例，默认1，即空间不足，该项目将缩小

如果所有项目的`flex-shrink`属性都为1，当空间不足时，都将等比例缩小。如果一个项目的`flex-shrink`属性为0，其他项目都为1，则空间不足时，前者不缩小。

负值对该属性无效。

```css
.item{
    flex-shrink:<number>;
}
```

##### 4.4 `flex-basis` 属性定义了在分配多余空间之前，项目占据的主轴空间（main size）。浏览器根据这个属性，计算主轴是否有多余空间。它的默认值为`auto`，即项目的本来大小。

它可以设为跟width或height属性一样的值（比如350px），则项目将占据固定空间。

```css
.item{
    flex-basis:<length> | auto; /*default auto*/
}
```

##### 4.5 `flex` 属性是`flex-grow`, `flex-shrink` 和 `flex-basis`的简写，默认值为`0 1 auto`。后两个属性可选。

该属性有两个快捷值：auto (1 1 auto) 和 none (0 0 auto)。

建议优先使用这个属性，而不是单独写三个分离的属性，因为浏览器会推算相关值。

```css
.item{
    flex:none | [ <flex-grow><flex-shrink> || <flex-basis>]
}
```

##### 4.6 `align-self` 属性允许单个项目有与其他项目不一样的对齐方式，可覆盖`align-items`属性。默认值为`auto`，表示继承父元素的`align-items`属性，如果没有父元素，则等同于`stretch`。

```css
.item{
    align-self:auto | flex-start | flex-end | center | baseline | stretch ;
}
```
